// src/lib/agents/mock-data.ts
import type {
  AgentType,
  AgentState,
  AgentAction,
  AgentApproval,
} from './types'

// ---- Mock Agent States ----

export const MOCK_AGENT_STATES: AgentState[] = [
  {
    id: 'mock-state-1',
    store_id: 'mock-store',
    agent_type: 'support',
    is_enabled: true,
    autonomy_level: 3,
    config: {},
    status: 'running',
    last_action_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2 min ago
    last_error: null,
    error_count: 0,
    total_actions: 147,
    total_approvals_requested: 12,
    total_approvals_granted: 10,
    total_approvals_rejected: 2,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-state-2',
    store_id: 'mock-store',
    agent_type: 'analytics',
    is_enabled: true,
    autonomy_level: 4,
    config: {},
    status: 'idle',
    last_action_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 min ago
    last_error: null,
    error_count: 0,
    total_actions: 89,
    total_approvals_requested: 3,
    total_approvals_granted: 3,
    total_approvals_rejected: 0,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-state-3',
    store_id: 'mock-store',
    agent_type: 'sales',
    is_enabled: true,
    autonomy_level: 3,
    config: {},
    status: 'waiting_approval',
    last_action_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    last_error: null,
    error_count: 0,
    total_actions: 56,
    total_approvals_requested: 8,
    total_approvals_granted: 6,
    total_approvals_rejected: 2,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-state-4',
    store_id: 'mock-store',
    agent_type: 'marketing',
    is_enabled: false,
    autonomy_level: 2,
    config: {},
    status: 'idle',
    last_action_at: null,
    last_error: null,
    error_count: 0,
    total_actions: 0,
    total_approvals_requested: 0,
    total_approvals_granted: 0,
    total_approvals_rejected: 0,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-state-5',
    store_id: 'mock-store',
    agent_type: 'technical',
    is_enabled: true,
    autonomy_level: 4,
    config: {},
    status: 'idle',
    last_action_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    last_error: null,
    error_count: 0,
    total_actions: 34,
    total_approvals_requested: 5,
    total_approvals_granted: 4,
    total_approvals_rejected: 1,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
]

// ---- Mock Activity Feed ----

export const MOCK_ACTIVITY_FEED: AgentAction[] = [
  {
    id: 'action-1',
    store_id: 'mock-store',
    agent_type: 'support',
    action_type: 'ticket_resolved',
    action_category: 'communication',
    summary: 'Resolved customer query about shipping delay for order #1847',
    details: { customer: 'Priya Sharma', resolution: 'Provided updated tracking link' },
    status: 'completed',
    execution_mode: 'auto',
    approval_id: null,
    related_entity_type: 'order',
    related_entity_id: '1847',
    model_used: 'gemini-2.0-flash',
    tokens_input: 1200,
    tokens_output: 450,
    estimated_cost_usd: 0.0003,
    api_costs: {},
    started_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1.5 * 60 * 1000).toISOString(),
    duration_ms: 3200,
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'action-2',
    store_id: 'mock-store',
    agent_type: 'analytics',
    action_type: 'daily_digest',
    action_category: 'analysis',
    summary: 'Generated daily business digest — revenue up 23% vs last Tuesday',
    details: { revenue_today: 47500, revenue_last_week: 38600 },
    status: 'completed',
    execution_mode: 'auto',
    approval_id: null,
    related_entity_type: null,
    related_entity_id: null,
    model_used: 'gemini-2.0-flash',
    tokens_input: 3500,
    tokens_output: 1200,
    estimated_cost_usd: 0.0008,
    api_costs: {},
    started_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 29 * 60 * 1000).toISOString(),
    duration_ms: 8500,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'action-3',
    store_id: 'mock-store',
    agent_type: 'sales',
    action_type: 'cart_recovery',
    action_category: 'campaign',
    summary: 'Sent recovery email to 5 abandoned carts with personalized 10% discount',
    details: { carts_targeted: 5, discount_percent: 10, template: 'recovery_gentle' },
    status: 'completed',
    execution_mode: 'auto',
    approval_id: null,
    related_entity_type: null,
    related_entity_id: null,
    model_used: 'gemini-2.0-flash',
    tokens_input: 2800,
    tokens_output: 900,
    estimated_cost_usd: 0.0006,
    api_costs: {},
    started_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
    duration_ms: 5200,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'action-4',
    store_id: 'mock-store',
    agent_type: 'technical',
    action_type: 'seo_update',
    action_category: 'optimization',
    summary: 'Updated meta descriptions for 12 products missing SEO tags',
    details: { products_updated: 12, field: 'meta_description' },
    status: 'completed',
    execution_mode: 'auto',
    approval_id: null,
    related_entity_type: 'product',
    related_entity_id: null,
    model_used: 'gemini-2.0-flash',
    tokens_input: 4200,
    tokens_output: 2800,
    estimated_cost_usd: 0.0012,
    api_costs: {},
    started_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1.95 * 60 * 60 * 1000).toISOString(),
    duration_ms: 18000,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'action-5',
    store_id: 'mock-store',
    agent_type: 'support',
    action_type: 'ticket_resolved',
    action_category: 'communication',
    summary: 'Answered product availability question on WhatsApp for Rajesh K.',
    details: { channel: 'whatsapp', customer: 'Rajesh K.' },
    status: 'completed',
    execution_mode: 'auto',
    approval_id: null,
    related_entity_type: null,
    related_entity_id: null,
    model_used: 'gemini-2.0-flash',
    tokens_input: 800,
    tokens_output: 350,
    estimated_cost_usd: 0.0002,
    api_costs: {},
    started_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 2.98 * 60 * 60 * 1000).toISOString(),
    duration_ms: 2100,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'action-6',
    store_id: 'mock-store',
    agent_type: 'analytics',
    action_type: 'anomaly_detected',
    action_category: 'analysis',
    summary: 'Detected unusual traffic spike — 3x normal visits from Instagram referral',
    details: { source: 'instagram', multiplier: 3.2, period: 'last_2_hours' },
    status: 'completed',
    execution_mode: 'auto',
    approval_id: null,
    related_entity_type: null,
    related_entity_id: null,
    model_used: 'gemini-2.0-flash',
    tokens_input: 1500,
    tokens_output: 600,
    estimated_cost_usd: 0.0004,
    api_costs: {},
    started_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 3.98 * 60 * 60 * 1000).toISOString(),
    duration_ms: 4500,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
]

// ---- Mock Pending Approvals ----

export const MOCK_APPROVALS: AgentApproval[] = [
  {
    id: 'approval-1',
    store_id: 'mock-store',
    agent_type: 'sales',
    action_type: 'discount_campaign',
    summary: 'Send 20% Diwali Sale discount to 156 loyal customers',
    reasoning: 'These customers have purchased 3+ times in the last 6 months. A 20% discount during Diwali has historically driven 4.2x ROI based on similar campaigns.',
    details: { discount_percent: 20, target_segment: 'loyal', customer_count: 156, estimated_cost: 12400 },
    priority: 'high',
    expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    resolved_by: null,
    resolved_at: null,
    rejection_reason: null,
    modifications: null,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'approval-2',
    store_id: 'mock-store',
    agent_type: 'support',
    action_type: 'refund',
    summary: 'Process ₹2,499 refund for order #1823 — customer received damaged item',
    reasoning: 'Customer provided photos of damaged packaging. Product (ceramic vase) is visibly cracked. Return policy covers damage in transit.',
    details: { order_id: '1823', amount: 2499, currency: 'INR', reason: 'damaged_in_transit' },
    priority: 'normal',
    expires_at: null,
    status: 'pending',
    resolved_by: null,
    resolved_at: null,
    rejection_reason: null,
    modifications: null,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'approval-3',
    store_id: 'mock-store',
    agent_type: 'technical',
    action_type: 'seo_update',
    summary: 'Rewrite product titles for 8 items to improve search ranking',
    reasoning: 'Current titles are too short (avg 3 words). Adding category and material keywords could improve organic traffic by an estimated 15-25%.',
    details: { products_affected: 8, change_type: 'title_rewrite', estimated_impact: '+15-25% organic' },
    priority: 'low',
    expires_at: null,
    status: 'pending',
    resolved_by: null,
    resolved_at: null,
    rejection_reason: null,
    modifications: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
]

// ---- Helpers ----

export function getAgentState(agentType: AgentType): AgentState | undefined {
  return MOCK_AGENT_STATES.find((s) => s.agent_type === agentType)
}

export function getEnabledAgentCount(): number {
  return MOCK_AGENT_STATES.filter((s) => s.is_enabled).length
}

export function getPendingApprovalCount(): number {
  return MOCK_APPROVALS.filter((a) => a.status === 'pending').length
}

export function getTotalActions(): number {
  return MOCK_AGENT_STATES.reduce((sum, s) => sum + s.total_actions, 0)
}

export function formatTimeAgo(dateString: string): string {
  const seconds = Math.floor((Date.now() - new Date(dateString).getTime()) / 1000)
  if (seconds < 60) return 'just now'
  const minutes = Math.floor(seconds / 60)
  if (minutes < 60) return `${minutes}m ago`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours}h ago`
  const days = Math.floor(hours / 24)
  return `${days}d ago`
}
