import { NextRequest, NextResponse } from 'next/server'
import { storeExists } from '@/lib/store/queries'

// Production domain configuration
const PRODUCTION_DOMAIN = process.env.NEXT_PUBLIC_PRODUCTION_DOMAIN || 'storeforge.site'
const IS_PRODUCTION = process.env.NODE_ENV === 'production'
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'

function getStoreUrl(slug: string): string {
  if (IS_PRODUCTION) {
    return `https://${slug}.${PRODUCTION_DOMAIN}`
  }
  return `${BASE_URL}/${slug}`
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ storeSlug: string }> }
) {
  try {
    const { storeSlug } = await params

    // Check if store exists
    const exists = await storeExists(storeSlug)

    if (!exists) {
      return new NextResponse('Store not found', { status: 404 })
    }

    const storeUrl = getStoreUrl(storeSlug)

    // Generate robots.txt content
    const robotsTxt = `# Robots.txt for ${storeSlug}
# Generated by StoreForge

User-agent: *
Allow: /
Allow: /products/
Allow: /collections/
Allow: /about
Allow: /contact

# Disallow sensitive paths
Disallow: /cart
Disallow: /checkout
Disallow: /order-confirmation
Disallow: /api/

# Crawl delay (optional, be nice to the server)
Crawl-delay: 1

# Sitemap location
Sitemap: ${storeUrl}/sitemap.xml
`

    return new NextResponse(robotsTxt, {
      headers: {
        'Content-Type': 'text/plain',
        'Cache-Control': 'public, max-age=86400, s-maxage=86400'
      }
    })
  } catch (error) {
    console.error('Robots.txt generation error:', error)
    return new NextResponse('Error generating robots.txt', { status: 500 })
  }
}
